version: '3.8'

services:
  segs_db:
    container_name: service-segs-db
    image: postgres:alpine3.18
    restart: always
    environment:
      POSTGRES_USER: thiranger
      POSTGRES_PASSWORD: qwertysegs2140
      POSTGRES_DB: service-segs-db
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - 5432:5432
    volumes:
      - ./pginit.sql:/docker-entrypoint-initdb.d/init.sql
      - service-segs-dbvol:/var/lib/postgresql/data/pgdata
  segs_svc:
    container_name: service-segs
    build:
      context: ..
      dockerfile: ./build/service-segs/Dockerfile
    depends_on:
      segs_db:
        condition: service_started
    ports:
      - 8080:8080
    volumes:
      - service-segs-csv:/some/path/to/mounted/volume

volumes:
  service-segs-dbvol:
  service-segs-csv:
