version: '3.8'

services:
  segs_db:
    container_name: service-segs-db
    image: postgres:alpine3.18
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=root
    volumes:
      - ./pginit.sql:/docker-entrypoint-initdb.d/init.sql
  segs_svc:
    container_name: service-segs
    build:
      context: ..
      dockerfile: ./build/service-segs/Dockerfile
    depends_on:
      segs_db:
        condition: service_started
    ports:
      - 8080:8080
    volumes:
      - csv_vol:/some/path/to/mounted/volume
