apiVersion: v1
kind: ConfigMap
metadata:
  name: service-segs-cfg
data:
  PG_PASSWORD: qwertysegs2140
  CSV_PATH: /mnt/csv-reports-pvc
  SERVICE_PORT: 8080
---
apiVersion: v1
kind: Pod
metadata:
  labels:
    app: segments
  name: service-segs
spec:
  containers:
  - name: db
    image: localhost/service-segs-db
    env:
    - name: POSTGRES_PASSWORD
      valueFrom:
        configMapKeyRef:
          name: service-segs-cfg
          key: PG_PASSWORD
          optional: false
    volumeMounts:
    - mountPath: /var/lib/postgresql/data
      name: db-pvc
  - name: app
    image: localhost/service-segs-app
    envFrom:
    - configMapRef:
        name: service-segs-cfg
        optional: false
    ports:
    - containerPort: 8080
      hostPort: 8080
    volumeMounts:
    - mountPath: /mnt/csv-reports-pvc
      name: app-pvc
  volumes:
  - name: db-pvc
    persistentVolumeClaim:
      claimName: service-segs-db
  - name: app-pvc
    persistentVolumeClaim:
      claimName: service-segs-csv
